### ISSUE TITLE
smart_proxy_abrt should accept for enabled setting values like http, https

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/smart_proxy_abrt#5]
Based on the discussion from https://github.com/theforeman/puppet-foreman_proxy/issues/191#issuecomment-140715736, it seems that the setting "enabled" should accept also as values "http" and "https".

**Comment by mmilata** [comment]
Do you think it's sufficient to reverse the check in https://github.com/theforeman/smart_proxy_abrt/blob/master/bin/smart-proxy-abrt-send#L27 to `if AbrtProxy::Plugin.settings.enabled == false`?

I haven't been working on this plugin for some time but this seems like an easy fix.

**Comment by ekohl** [comment]
That could work or maybe you can reuse the enabled logic from the smartproxy code?

**Comment by mmilata** [comment]
Does 79734ba look good? If so I can release new version of the plugin.
